name = "image-generation"
compatibility_date = "2024-11-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[ai]
binding = "AI" # available in your Worker code on `env.AI`